feat: 유저 정보 가져오기
cookie-parking/coopa-server pull request #12
Opened 2021-01-03 20:33 UTC by gngsn

### 유저 정보 불러오기

- `id`, `email`, `state message`, `누적 쿠키수`, `저장된 쿠키 조회 수` 를 확인할 수 있음

2021-01-04 12:02 UTC, bluayer requested changes
크게 수정할 부분은 없고, 궁금한 점들 달아놨음!

2021-01-04 12:02 UTC, bluayer commented on src/app.ts
> +
여기에 라인이 두 줄 이상 생긴 이유는 어떤걸까용ㅋㅋㅋㅋ

2021-01-04 12:33 UTC, gngsn commented on src/domain/usecase/user/getUserInfo.ts
> +                'stateMsg',
한줄 소개!

2021-01-04 12:35 UTC, gngsn commented on src/domain/usecase/cookie/readCookie.ts
> +            }
null check 안해주면 null 일 수 있다는 eslint 경고가 떠서 commit이 안되던데... 혹시 다른 방법있나?

2021-01-04 12:57 UTC, bluayer commented on src/domain/usecase/cookie/readCookie.ts
> +            }
근데 궁금한게 Cookie 안에 readCnt가 이미 있는거 아냐?
cookie 전체 컬럼들을 불러와서 단순하게 cookie.readCnt를 했으면 되었을 꺼 같은데??

2021-01-04 12:58 UTC, bluayer commented on src/domain/usecase/cookie/readCookie.ts
> +            }
그리고 일단 코드레벨에서도 나였으면 !beforeCnt를 했을꺼 같고
만약 성능을 생각해서 해당 컬럼만 뽑은거라면,
우리 컬럼 수가 적어서 * <= 이걸 쓰는거 하고 아마 컬럼 하나만 뽑아오는 거하고 성능차이 크게 없을꺼야!! 그래서 그냥 전체를 가져와도 문제 없음!

2021-01-04 13:00 UTC, bluayer commented on src/domain/usecase/user/getUserInfo.ts
> +                'stateMsg',
ㅋㅋㅋㅋㅋㅋ 이름을 introduction 같은 걸로 했어야 하지 않을까?ㅋㅋㅋ
진짜 상상도 못한 이름이었다ㅋㅋㅋ

2021-01-04 15:08 UTC, gngsn commented on src/domain/usecase/user/getUserInfo.ts
> +                'stateMsg',
ㅋㅋㅋㅋㅋㅋㅋ 나도 지금 보니까 아닌 것 같아....

2021-01-04 17:16 UTC, gngsn commented on src/domain/usecase/cookie/readCookie.ts
> +            }
!beaforeCnt을 하면 beaforeCnt 가 0일 때에도 조건이 true가 되어서 일부러 == null 로 했어!

2021-01-05 00:41 UTC, bluayer commented on src/domain/usecase/cookie/readCookie.ts
> +            }
굳굳~~

2021-01-05 00:43 UTC, bluayer approved these changes
굳굳~~

2021-01-05 00:48 UTC, merged