feat: 쿠키 검색
cookie-parking/coopa-server pull request #13
Opened 2021-01-04 12:25 UTC by bluayer

### Summary
- 쿠키의 title과 content로 검색 가능하게 함

### Needs more than 10 min?
Nope. 사실상 디렉토리 검색과 거의 유사

2021-01-04 15:30 UTC, gngsn requested changes
소심하게 내 의견을 적어봣오..

2021-01-04 15:30 UTC, gngsn commented on src/adapter/router/cookie.ts
> +}
이런 건 DTO 를 따로 만드는 것도 좋을 것 같아

2021-01-04 15:30 UTC, gngsn commented on src/adapter/router/cookie.ts
>      router.post<404 | 400 |  201, string | {}>('/', async (req: Request, __) => {
```suggestion
    router.post<404 | 400 | 201, string | {}>('/', async (req: Request, __) => {
```

2021-01-04 15:30 UTC, gngsn commented on src/adapter/router/cookie.ts
> +            })
usecase에서 처리하고 넘겨주면 조금 더 깔끔해보이지 않을까?

2021-01-05 00:34 UTC, bluayer commented on src/adapter/router/cookie.ts
> +            })
UseCase에서 처리하고 넘겨주면 단기적으로 깔끔해 보일 수는 있지만,
클라이언트에게 보낼 응답을 구성하는 건 router의 책임이라고 생각해!
아마 이런 응답들이 다양해지고, 비즈니스 로직이 무거워질 수록 UseCase만 비대해지는 현상이 생기겠지?
이런 이유로 책임을 분산하기 위해서 router에 클라이언트가 볼 응답을 구성하는 책임을 위임하는게 나는 좋다고 생각해!

2021-01-05 00:37 UTC, bluayer commented on src/adapter/router/cookie.ts
> +}
나도 DTO 만들자는 의견에 동의하고, 
보통 DTO를 만드는 이유는 계층 간의 데이터 이동이 원활하게 하기 위해서인데
만약 DTO를 만들기 시작하면 사실상 엔티티도 실체 구현 클래스로 존재해야 하고,
다른 UseCase들에서도 DTO를 쓰는 방향으로 움직이는 게 좋아.

그리고 사실 응답의 타입들을 체크하기 위한 용도 정도의 interface인 상황이기 때문에,
나중에 기능들이 다 만들어지고 나서, 우리끼리 더 좋은 아키텍쳐에 대해 얘기하며 수정할 때
다 같이 함께 반영해보면 좋을 꺼라고 생각!

2021-01-05 13:18 UTC, merged