feat: 구글 로그인 생성
cookie-parking/coopa-server pull request #18
Opened 2021-01-05 19:09 UTC by gngsn

### 구글 로그인 기능 추가

- social id의 존재 여부로 소셜로그인 대상자인지 판별
- 소셜 로그인 시 password & salt 가 존재하지 않기 때문에 null값이 가능한 값으로 수정
- jwt를 따로 발급해서 google에서 제공하는 access token 검사를 따로 하진 않음

2021-01-06 04:53 UTC, bluayer requested changes
전체적으로 크게 수정할 부분은 없지만, 중간 중간 필요한 부분들을 코멘트!

2021-01-06 04:53 UTC, bluayer commented on src/domain/usecase/user/googleAuth.ts
> +        let message = '구글 계정으로 로그인 성공';
message는 router의 책임이야!
UseCase에서 만들어서 나가지 말고, router가 알 수 있게 enum type 같은걸로 보내고
router에서 해당 메시지를 적는 형식으로 가자!

2021-01-06 04:53 UTC, bluayer commented on src/domain/usecase/user/googleAuth.ts
> +            }
<< 의문점 >>
1. 지금 어차피 구글 로그인만 남는거 아닌가?
2. 구글로그인, 로컬로그인 상관없이 jwt는 같은 형식으로 만들어지는데, socialId를 체크하는 이유가 어떤거지?
만약 같은 이메일을 가지고 있는 로컬 유저를 파악하고 싶은거였다면, 
해당 이메일이 구글 이메일이기 때문에 socialId를 채워주면 기존 로컬 유저입장에서는 구글 로그인으로도 연동이 됐구나! 이렇게 되지 않을까?

2021-01-06 04:53 UTC, bluayer commented on src/domain/usecase/user/login.ts
> +        }
GoolgleAuth에서 이미 다 알아서 가입 혹은 로그인을 시키는데, 이 부분이 필요한 이유가 어떤거지?

2021-01-06 04:53 UTC, bluayer commented on src/domain/usecase/user/signup.ts
> +            profileImage: '',
차라리 NULL 값을 넣는게 좋을 꺼 같아!
만약 이렇게 되면 default가 NULL이 아니라 empty string이 될꺼라서
쿼리나 코드에서 empty string인지 체크해야 할꺼야!

2021-01-06 04:53 UTC, bluayer commented on src/adapter/router/auth.ts
> +        const { name, email, profileImage, googleId } = req.body;
google login이후 받는 토큰은 저장 안 하는건가?

2021-01-06 06:28 UTC, gngsn commented on src/domain/usecase/user/googleAuth.ts
> +            }
2번째 말이 잘 이해가질 않네
기존 gmail 유저가 접근하면 social Id 를 채워주자는 말인가?

2021-01-06 06:29 UTC, gngsn commented on src/domain/usecase/user/login.ts
> +        }
null check 를 안하면 trpescript 에서 경고가 떠서..

2021-01-06 06:29 UTC, gngsn commented on src/domain/usecase/user/signup.ts
> +            profileImage: '',
아 맞네ㅔ 알았어

2021-01-06 06:31 UTC, bluayer commented on src/domain/usecase/user/googleAuth.ts
> +            }
기존에 gmail로 가입한 local 유저가, google login으로 접근하면 socialId를 채우자는거였음!

2021-01-06 06:34 UTC, gngsn commented on src/domain/usecase/user/googleAuth.ts
> +            }
아 그래 좋은 것 같아 수정할게 !

2021-01-06 06:38 UTC, bluayer commented on src/domain/usecase/user/login.ts
> +        }
```javascript
const { password: userPwd, salt: userSalt } = user;
```
이 부분을 밑에 처럼 바꾸면 저렇게 체크 안 해도 되긴 할 텐데... 필요할 수도 있겠군...
```suggestion
        const userPwd = user.password!;
        const userSalt = user.salt!;
```

2021-01-06 07:03 UTC, gngsn commented on src/adapter/router/auth.ts
> +        const { name, email, profileImage, googleId } = req.body;
어떤 토큰 말하는 거지? google login access token ?

2021-01-06 07:52 UTC, bluayer commented on src/adapter/router/auth.ts
> +        const { name, email, profileImage, googleId } = req.body;
응응

2021-01-07 07:37 UTC, gngsn commented on src/adapter/router/auth.ts
> +        const { name, email, profileImage, googleId } = req.body;
지금이나 앱잼 때에는 저장할 필요가 없다고 생각해서 안만들었어!

2021-01-07 08:01 UTC, gngsn commented
### 수정한 부분
- 회원가입/로그인을 구분 하는 res message 부분 삭제 ( 기획에 물어봤는데 굳이 필요없다고 해서 )
- profileImage 필수 값으로 변경

2021-01-07 12:00 UTC, bluayer approved these changes
ㅇㅍㄹㅂ!

2021-01-07 12:00 UTC, merged